name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel
        uses: vercel/github-action@v20.2.1
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: FqchvDTddURRbw72LcD9xWjdEBkR
